repos:
  - repo: local
    hooks:
      - id: lint-check
        name: Lint check
        entry: uv run poe lint
        language: system
        pass_filenames: false

      - id: type-check
        name: Type check
        entry: uv run poe type-check
        language: system
        pass_filenames: false
