repos:
  - repo: local
    hooks:
      - id: lint
        name: Linting
        entry: make lint
        language: system
        pass_filenames: false

      - id: type-check
        name: Type checking
        entry: make type-check
        language: system
        pass_filenames: false

      - id: unit-tests
        name: Unit tests
        entry: make unit-tests
        language: system
        pass_filenames: false

      - id: check-version-conflict
        name: Check version conflict
        entry: make check-version-conflict
        language: system
        pass_filenames: false
