# % set extras = [cookiecutter.crawler_type]
# % if cookiecutter.http_client == 'curl-impersonate'
# % do extras.append('curl-impersonate')
# % endif

# % if cookiecutter.package_manager == 'poetry'
[tool.poetry]
name = "{{cookiecutter.project_name}}"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.9"
# % if cookiecutter.enable_apify_integration
apify = "*"
# % endif
crawlee = {version = "*", extras = {{ extras | tojson }}}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
# % else
[project]
name = "{{cookiecutter.project_name}}"
version = "0.0.1"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
requires-python = ">=3.9"
# % endif
