name: Doc checks

on:
  # Runs when manually triggered from the GitHub UI.
  workflow_dispatch:

  # Runs when invoked by another workflow.
  workflow_call:
    secrets:
      APIFY_SIGNING_TOKEN:
        required: false

jobs:
  doc_checks:
    name: Doc checks
    uses: apify/workflows/.github/workflows/python_docs_check.yaml@main
    secrets:
      APIFY_SIGNING_TOKEN: ${{ secrets.APIFY_SIGNING_TOKEN }}
