name: Check changelog entry

on:
  workflow_call:

jobs:
  check_changelog_entry:
    name: Check changelog entry
    runs-on: ubuntu-latest
    if: (!startsWith(github.event.pull_request.title, 'docs:'))

    steps:
      # We need to check out the head commit in case of PRs, and the default ref otherwise (during release).
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || '' }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          pipx install --python ${{ env.pythonLocation }} poetry
          make install-dev

      - name: Check changelog entry
        run: make check-changelog-entry
